name: nekonata_map_example
description: "Demonstrates how to use the nekonata_map plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1

  nekonata_map:
    # When depending on this package from a real application you should use:
    #   nekonata_map: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner:
  custom_lint:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis:

flutter:
  uses-material-design: true
